import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import connectToDatabase from "@/lib/mongodb";
import DiagnosisLog from "@/lib/models/DiagnosisLog";
import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export async function POST(req: Request) {
    try {
        const session = await getServerSession(authOptions);
        if (!session || session.user.role !== "Doctor") {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }

        const { symptoms, age, gender, history, patientId } = await req.json();

        if (!symptoms) {
            return NextResponse.json({ error: "Symptoms are required" }, { status: 400 });
        }

        const prompt = `
      You are an expert AI clinical assistant helping a doctor. 
      Patient details:
      - Age: ${age || "Unknown"}
      - Gender: ${gender || "Unknown"}
      - Symptoms: ${symptoms}
      - Medical History: ${history || "None provided"}

      Please provide:
      1. A list of possible conditions.
      2. A designated Risk Level (must be exactly one of: Low, Medium, High, Critical).
      3. Suggested medical tests.

      Format the output clearly. Start the risk level line exactly as "Risk Level: [Level]" so it can be parsed.
    `;

        let aiResponseText = "";
        let riskLevel = "Medium";

        try {
            const response = await ai.models.generateContent({
                model: "gemini-2.5-flash",
                contents: prompt,
            });

            aiResponseText = response.text || "No response generated by AI.";

            const riskMatch = aiResponseText.match(/Risk Level:\s*(Low|Medium|High|Critical)/i);
            if (riskMatch && riskMatch[1]) {
                riskLevel = riskMatch[1].charAt(0).toUpperCase() + riskMatch[1].slice(1).toLowerCase();
            }
        } catch (aiError) {
            console.error("Gemini API Error:", aiError);
            aiResponseText = "AI Service temporarily unavailable. Please rely on standard medical protocols.";
            riskLevel = "Medium";
        }

        await connectToDatabase();

        const newDiagnosisLog = await DiagnosisLog.create({
            symptoms,
            aiResponse: aiResponseText,
            riskLevel,
            doctorId: session.user.id,
            patientId: patientId || undefined,
            age: age ? Number(age) : undefined,
            gender: gender || undefined,
        });

        return NextResponse.json({
            diagnosis: newDiagnosisLog
        }, { status: 200 });

    } catch (error: any) {
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
